# Purpose: 로컬 .env 설정을 유지하면서, Docker 환경에서만 DB 주소를 가로채서 변경함
x-common: &common
    image: chsproject-docker
    env_file:
      - .env
    networks:
      - chs-network
    restart: always
    environment: &common-env
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      JAVA_OPTS: -Xms128m -Xmx384m -XX:+UseSerialGC
      DATASOURCE_URL: jdbc:mysql://mysql-db:3306/home-db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
      REDIS_HOST: chs-redis


services:
  app1:
    <<: *common
    container_name: chs-app-1
    ports:
      - "8080:8080"
    environment:
      <<: *common-env
      SERVER_NAME: DOCKER1
      TELEGRAM_MODE: polling
    deploy:
      resources:
        limits:
          memory: 384M

  app2:
    <<: *common
    container_name: chs-app-2
    ports:
      - "8081:8080"
    environment:
      <<: *common-env
      SERVER_NAME: DOCKER2
      TELEGRAM_MODE: polling
    deploy:
      resources:
        limits:
          memory: 384M

  redis:
    image: redis:7-alpine
    container_name: chs-redis
    ports:
      - "6379:6379"
    networks:
      - chs-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 64M
networks:
  chs-network:
    name: ubuntu_default
    external: true
