# \uC2A4\uD504\uB9C1 \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984
spring.application.name=springboot
# \uC790\uB3D9 \uBE4C\uB4DC \uB9C9\uAE30
spring.devtools.restart.enabled=false
# \uC2A4\uCF00\uC974\uB7EC \uC2E4\uD589\uC5EC\uBD80 (local : X , real : O) :true \uAC00 \uC788\uC73C\uBA74 \uD658\uACBD\uBCC0\uC218 \uCC38\uC870 \uC2E4\uD328\uC2DC true \uB85C \uB3D9\uC791\uD558\uAC8C\uD568
spring.task.scheduling.enabled=${SCHEDULING_ENABLED:true}
# H2 \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC124\uC815
# spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./weatherdb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA/Hibernate \uC124\uC815
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

# 1. DB \uC5F0\uACB0 \uC124\uC815 (EC2 \uD37C\uBE14\uB9AD IP\uB97C \uB123\uC73C\uC138\uC694)
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PW}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA/Hibernate \uC124\uC815 (\uD575\uC2EC!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# MySQL 8.0 \uBC84\uC804\uC5D0 \uB9DE\uB294 \uBC29\uC5B8 \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Swagger UI \uC811\uC18D \uACBD\uB85C \uC124\uC815 (\uAE30\uBCF8\uAC12\uC740 /swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html
# API \uBA85\uC138\uC11C \uADF8\uB8F9 \uC774\uB984
springdoc.api-docs.path=/api-docs

# \uAE30\uC0C1\uCCAD API \uC124\uC815 (\uC6B0\uB9AC\uAC00 \uCD94\uAC00\uD560 \uAC83)
weather.api.service-key=${WEATHER_API_SERVICE_KEY}
weather.api.base-url=${WEATHER_API_BASE_URL}